version: '3.8'

networks:
  monitor:
    driver: bridge

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - /argos/loki/loki-config.yaml:/etc/loki/loki-config.yaml
    command: --config.file=/etc/loki/loki-config.yaml
    logging:
      driver: "loki:latest"
    networks:
      - monitor
    restart: always
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - /argos/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: --config.file=/etc/promtail/promtail-config.yaml
    logging:
      driver: "loki:latest"
    networks:
      - monitor
    restart: always
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    logging:
      driver: "loki:latest"
    networks:
      - monitor
    restart: always
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /argos/prometheus/prometheus.yml://etc/prometheus/prometheus.yml
      - /argos/prometheus/data:/prometheus
    logging:
      driver: "loki:latest"
    networks:
      - monitor
    restart: always
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - '9100:9100'
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
    logging:
      driver: "loki:latest"
    networks:
      - monitor
    restart: always
    
    