apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: server
    url: ${LOKI_URL}
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: server
    url: ${PROM_URL}
    jsonData:
      maxLines: 1000
