apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: direct
    url: http://localhost:3100
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: direct
    url: http://localhost:9090
    jsonData:
      maxLines: 1000
